# Generated by Django 5.2.1 on 2025-05-26 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NameRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa')),
                ('country', models.CharField(max_length=100, verbose_name='Kraj/Państwo')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Kod pocztowy')),
                ('status', models.CharField(choices=[('free', 'Wolna'), ('reserved', 'W trakcie rejestracji'), ('taken', 'Zajęta')], default='free', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Rejestracja nazwy',
                'verbose_name_plural': 'Rejestracje nazw',
            },
        ),
    ]
